# ThoroughBet Simulation


## Load necessary modules

In [1]:
import numpy as np

from thbmodel.utils import timestamp, YEAR, settings
from thbmodel.utils.arrayview import ArrayView, TimeseriesView

from thbmodel.prediction.models.fit_model import TSModel
from thbmodel.prediction.models.model_parameters import ModelParameters
from thbmodel.prediction.models.factor_management import FactorList
from thbmodel.prediction.models.preprocessing import load_slices

from thbmodel.prediction.models.prediction import factornames_trimmed
from thbmodel.prediction.models.parameters import factor_build_end

### Load data

In [2]:
settings.paths.join('racing_data_azd.av.bcolz')

'/home/oleg/thbmodel/racing_data/racing_data_azd.av.bcolz'

In [3]:
av = ArrayView.from_file(settings.paths.join('racing_data_azd.av.bcolz'))

In [4]:
tsav = load_slices()

### Preprocessing

In [5]:
pars = ModelParameters(av, oos_start=float(timestamp('2017-05-01')), depth=1, lmbd=10, verbose=False)

In [6]:
fl = FactorList.from_av(av, factornames_trimmed)

In [7]:
fl.preprocess(pars)
factors = fl.asmatrix()

In [8]:
from datetime import datetime
print 'factor_build_end  ',(datetime.utcfromtimestamp(pars.build_end))
print 'oos_start  ',(datetime.utcfromtimestamp(pars.oos_start))
print 'av_end  ',(datetime.utcfromtimestamp(pars._av_end))

factor_build_end   2016-03-01 00:00:00
oos_start   2017-05-01 00:00:00
av_end   2017-08-22 02:30:00


## Fit conditional logit model

In [9]:
tsmod = TSModel(factors, tsav, pars)

In [10]:
tsmod.fit_slices()
print 'LL................'
print tsmod.stats2.ll

thbmodel/prediction/models/fit_model.py:150: RuntimeWarning: divide by zero encountered in log
  stats, self.step2probs[sl] = self.concat_and_fit(strata, result, nonrunner, [fback, flay, np.log(probs)], ts_idx, valid2, verbose=False, step=2)


LL................
[[-1841.71211771 -2014.64783185 -2014.64783185]
 [-1846.09995945 -2010.17246104 -2010.17246104]
 [-1850.45158892 -2005.74888357 -2005.74888357]
 [-1852.84712372 -2001.06102244 -2001.06102244]
 [-1865.64087989 -1985.50064259 -1985.50064259]
 [-1876.45162575 -1977.58747572 -1977.58747572]
 [-1905.02665597 -1965.17813647 -1965.17813647]
 [-1915.51116973 -1957.48644079 -1957.48644079]
 [-1918.95666233 -1957.59955272 -1957.59955272]
 [-1922.13952769 -1952.82468284 -1952.82468284]
 [           nan            nan            nan]]


In [13]:
from thbmodel.prediction.tools.clustering import write_dic_to_simdata

#write_dic_to_simdata('new_factors_direction_new_code.p', new_model.step1probs, new_model.eff_coefs, oos, av =av)
write_dic_to_simdata('old_model_54components.p', tsmod.step1probs, tsmod.eff_coefs, pars.oos, av=av)

In [14]:
def new_factors_array (X, predict_mask =pars.model_mask):
    
    
    factors_new = np.zeros((X.shape[1], predict_mask.shape[0]))
    factors_new[:, predict_mask] = X.T
    
    return factors_new

In [15]:
# создаем дата фрейм из данных 
def DF(mask, factors, av, factors_names, other_names):
    
    import pandas as pd
    
    df = pd.DataFrame(data =factors[:, mask].T , columns = factors_names)
    for col in other_names :
        
        df[col] = av[col][mask]
        
    return df

In [17]:
import pandas as pd
pd.set_option('display.max_columns', 90)
n,m = factors.shape
col_names = ['f{}'.format(i) for i in range(1,n+1)]

df = DF (tsmod.params.model_mask, factors, av, col_names, ['event_id', 'runner_id', 'result', 'start_time', 
                                                           'jockey', 'trainer', 'prize'])
df['is1'] = tsmod.params.is1 [tsmod.params.model_mask]
df['is2'] = tsmod.params.is2 [tsmod.params.model_mask]
df['oos'] = tsmod.params.oos [tsmod.params.model_mask]


df.head()

f1        f2        f3        f4        f5        f6        f7  \
0  0.275018 -2.136733  0.538481 -0.249552  0.000000  0.648431  1.956461   
1  0.275018 -1.165283  0.760248 -0.017615 -0.006324 -0.089657 -0.293469   
2  0.275018 -1.019235 -0.620884 -0.054585  0.000418  0.343413 -0.586938   
3  0.275018 -0.124600  0.648707 -0.129885 -0.036245 -0.044074 -0.586938   
4 -0.687549  1.723630 -0.606623 -0.249552  0.000000 -0.202362 -0.313034   

         f8        f9       f10       f11       f12       f13       f14  \
0 -0.350451  1.765546  0.041709  0.566215  0.186418  1.757950 -2.006400   
1  0.028194  0.300362  0.301038  0.397894  0.302236 -0.428768 -0.862865   
2 -0.087615  0.240985  0.514035  0.535161  0.260576  0.007447 -0.930042   
3 -0.025961  0.254463  0.217953  0.044346  0.076432 -0.222316 -0.642565   
4  0.242896  0.144210 -0.155554  0.155252 -0.062139 -0.481582  2.027093   

        f15       f16       f17       f18       f19       f20       f21  \
0  0.350451 -0.146133  0.115240  0.000000 -0.181759  0.819832  0.128090   
1 -0.027642  0.071812  0.081162  0.027632 -0.535525 -0.562630 -0.395142   
2  0.087825  0.028731 -0.023594  0.119720 -0.567414 -0.434029  0.408481   
3  0.026061  0.118026 -0.091568  0.117425  0.299917 -1.446763  0.385371   
4 -0.242895  0.287826 -0.218564  0.271644  0.136029  1.945092  0.455057   

        f22       f23       f24       f25       f26       f27       f28  \
0 -2.007462  1.197907  0.000000  0.000000 -0.159251  1.247866  0.417520   
1 -0.449051 -0.573235  0.128626 -0.078590  0.193096  0.903727  0.075159   
2 -0.358223 -0.573235  0.219751  0.047266  0.359501  0.970164 -0.068555   
3  0.554291 -0.573235 -0.034618 -0.059661  0.820580 -6.476758 -0.106326   
4  1.366263 -0.573235  0.000000  0.206791 -0.022349  0.965077  0.032116   

        f29       f30       f31       f32       f33       f34       f35  \
0  0.819386 -2.570586  1.112466 -0.490569  0.000000 -0.298519  0.484388   
1  0.722918 -0.696183  0.904835 -0.086411  0.446376 -0.200426  0.060539   
2  0.169833  6.615283 -0.501394  0.872033 -0.311032  0.056299  1.078648   
3  0.214215 -0.610506 -0.115307  0.016959 -0.102501  0.087229  0.735120   
4  0.589176 -1.529798 -0.722877 -0.299929  0.000000  0.206902 -0.516705   

        f36       f37  f38       f39       f40       f41       f42       f43  \
0  0.314805  2.374919  0.0 -1.408942  0.120669 -0.940079 -0.407874  0.000000   
1  0.679282  1.038988  0.0 -1.148013 -0.243849 -0.551588  0.006630  0.408662   
2  0.362859  1.002002  0.0 -0.598422 -0.243849 -0.337185 -0.026138  0.418632   
3  0.293204  0.799318  0.0 -0.177459 -0.243849 -0.133236  0.097647  0.107262   
4 -0.651000 -2.356321  0.0  0.473027  0.162551 -0.445529 -0.483757  0.000000   

        f44       f45       f46       f47       f48       f49       f50  \
0  0.772860 -0.118808  0.059176  1.022655  0.000000  0.102526  0.614107   
1  0.772860  0.109651  4.479126  1.271640  0.300114 -0.190860  0.075975   
2  0.962685 -0.037129 -1.127538  0.091651  0.216035  0.054865  0.740658   
3  0.772860 -0.113422 -0.390880  0.257840  0.115497 -0.160653 -0.021746   
4 -2.027062  0.442830 -1.329056 -1.311230  0.000000 -0.035646 -0.209930   

        f51       f52       f53       f54  event_id  runner_id  result  \
0  0.895830  0.350452 -0.350448  0.310555    305646     355120       1   
1  0.124702 -0.027706  0.027719  0.062085    305646     419426       2   
2  0.147065  0.087724 -0.089675  0.171093    305646     419427       3   
3  0.120533  0.026054 -0.026648  0.094833    305646     419428       5   
4  0.397297 -0.242895  0.242897 -0.079439    305646     401539       6   

     start_time  jockey  trainer   prize   is1   is2    oos  
0  1.456841e+09    5598     5351  2911.0  True  True  False  
1  1.456841e+09      63       64  2911.0  True  True  False  
2  1.456841e+09    8135    10791  2911.0  True  True  False  
3  1.456841e+09      29      408  2911.0  True  True  False  
4  1.456841e+09   10807    10836  2911.0  True  True  False

In [18]:
from sklearn.decomposition import PCA
seed =7
n_components = 45
pca = PCA(n_components =n_components, random_state =seed)
name_pca = ['pca_f%s'%i for i in range(1, n_components+1)]

df_pca = pd.DataFrame(data = pca.fit_transform(df.loc[:,col_names]), columns =name_pca) 
    
pca_factors = new_factors_array(df_pca[name_pca])
pca_model = TSModel(pca_factors, tsav, pars)
pca_model.fit_slices()
    
print '{} PCA components'.format(n_components)
print 'LL................'
print pca_model.stats2.ll
print

45 PCA components
LL................
[[-1841.8231785  -2014.90686255 -2014.90686255]
 [-1846.20531733 -2010.34462411 -2010.34462411]
 [-1850.57395287 -2005.97976507 -2005.97976507]
 [-1852.98106992 -2001.31656051 -2001.31656051]
 [-1865.83606332 -1985.54833737 -1985.54833737]
 [-1876.70004601 -1977.35229545 -1977.35229545]
 [-1905.35743324 -1965.10990572 -1965.10990572]
 [-1916.09718726 -1957.5457566  -1957.5457566 ]
 [-1919.6128079  -1957.55827274 -1957.55827274]
 [-1922.96478944 -1952.43428967 -1952.43428967]
 [           nan            nan            nan]]



In [20]:
factors_names = np.array(['f_%s'%(i+1)  for i in range(pca_factors.shape[0])])

In [54]:
threshold =1.
names_factors =[]
_int_factors =[]
student_t_factors = []

for i in range(pca_factors.shape[0]):
    new_factors = pca_factors[i:,:] * pca_factors[i,:]
    new_factors = np.vstack((pca_factors, new_factors))
    print 'pca_f',(i+1)
    print new_factors.shape
    
    new_model = TSModel(new_factors, tsav, pars)
    new_model.fit_slices(fit_afresh=True)

    print 'll  for production factors %s'%(i+1)
    print new_model.stats1.ll
    print
    
    f = '*pca_f%s'%(i+1)
    factors_names = [x+f for x in name_pca[i:]]
    _int_factors += [(x,i) for x in range(i, pca_factors.shape[0])])
    names_factors.append(factors_names)
    mean_student_t = new_model.stats1.student_t[:,47:].mean(axis =0)
    student_t_factors.append(mean_student_t)
    mask_factors = (mean_student_t > threshold)
    
    
    names_important = np.array(factors_names)[mask_factors]
    print 'important factors len', len(names_important)
    print names_important
    
    print '......................'
    new_factors = np.vstack((pca_factors, new_factors[mask_factors,:]))
    new_model = TSModel(new_factors, tsav, pars)
    new_model.fit_slices(fit_afresh=True)
    print 
    print 'll   for only important factors '
    print new_model.stats1.ll

pca_f 1
(90, 1805375)
ll  for production factors 1
[[-1839.33224854 -1839.33224854 -2018.10169031]
 [-1843.60231941 -1843.60231941 -2013.85605178]
 [-1848.01578716 -1848.01578716 -2009.61348704]
 [-1850.38556713 -1850.38556713 -2004.854583  ]
 [-1863.23228397 -1863.23228397 -1989.26828745]
 [-1874.22210594 -1874.22210594 -1981.10559524]
 [-1903.03134973 -1903.03134973 -1968.81578522]
 [-1913.6505794  -1913.6505794  -1961.08624102]
 [-1917.29118644 -1917.29118644 -1961.11196898]
 [-1920.59622241 -1920.59622241 -1955.95153837]
 [           nan            nan            nan]]

important factors len 15
['pca_f2*pca_f1' 'pca_f7*pca_f1' 'pca_f12*pca_f1' 'pca_f15*pca_f1'
 'pca_f16*pca_f1' 'pca_f17*pca_f1' 'pca_f19*pca_f1' 'pca_f22*pca_f1'
 'pca_f23*pca_f1' 'pca_f25*pca_f1' 'pca_f27*pca_f1' 'pca_f29*pca_f1'
 'pca_f31*pca_f1' 'pca_f39*pca_f1' 'pca_f41*pca_f1']
......................


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 90 but corresponding boolean dimension is 45



ll   for only important factors 
[[-1841.82890684 -1841.82890684 -2014.94005721]
 [-1846.21099955 -1846.21099955 -2010.43946739]
 [-1850.57975365 -1850.57975365 -2006.09111658]
 [-1852.98682071 -1852.98682071 -2001.45797987]
 [-1865.84285438 -1865.84285438 -1985.82734998]
 [-1876.70698083 -1876.70698083 -1977.75725377]
 [-1905.365866   -1905.365866   -1965.47771651]
 [-1916.10782275 -1916.10782275 -1957.81820743]
 [-1919.62350491 -1919.62350491 -1957.83553662]
 [-1922.97515669 -1922.97515669 -1952.63753475]
 [           nan            nan            nan]]
pca_f 2
(89, 1805375)
ll  for production factors 2
[[-1840.41404586 -1840.41404586 -2016.23741499]
 [-1844.82408331 -1844.82408331 -2011.65696619]
 [-1849.18895423 -1849.18895423 -2007.26830234]
 [-1851.66581885 -1851.66581885 -2002.59152312]
 [-1864.30761188 -1864.30761188 -1987.15651697]
 [-1875.06951224 -1875.06951224 -1979.40291524]
 [-1903.794197   -1903.794197   -1967.01489173]
 [-1914.32933272 -1914.32933272 -1959.46139794]
 [

/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 89 but corresponding boolean dimension is 44



ll   for only important factors 
[[-1841.85836931 -1841.85836931 -2014.93145956]
 [-1846.24232909 -1846.24232909 -2010.42412483]
 [-1850.61150878 -1850.61150878 -2006.07292637]
 [-1853.01942073 -1853.01942073 -2001.42864222]
 [-1865.87964471 -1865.87964471 -1985.75298758]
 [-1876.75102768 -1876.75102768 -1977.64902358]
 [-1905.40783079 -1905.40783079 -1965.35891241]
 [-1916.14388999 -1916.14388999 -1957.71619122]
 [-1919.66037651 -1919.66037651 -1957.71792068]
 [-1923.01459928 -1923.01459928 -1952.5241264 ]
 [           nan            nan            nan]]
pca_f 3
(88, 1805375)
ll  for production factors 3
[[-1840.42030238 -1840.42030238 -2015.98830191]
 [-1844.82434331 -1844.82434331 -2011.54052369]
 [-1849.13853694 -1849.13853694 -2007.17164486]
 [-1851.64097266 -1851.64097266 -2002.43622414]
 [-1864.40439501 -1864.40439501 -1986.56703323]
 [-1875.30754811 -1875.30754811 -1978.84781309]
 [-1903.84797396 -1903.84797396 -1966.3011331 ]
 [-1914.46179075 -1914.46179075 -1958.81192595]
 [

/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 88 but corresponding boolean dimension is 43



ll   for only important factors 
[[-1841.85859521 -1841.85859521 -2014.93380562]
 [-1846.2425581  -1846.2425581  -2010.426314  ]
 [-1850.61174688 -1850.61174688 -2006.07443387]
 [-1853.01971092 -1853.01971092 -2001.42931229]
 [-1865.87994268 -1865.87994268 -1985.75271378]
 [-1876.75140472 -1876.75140472 -1977.64904308]
 [-1905.4083587  -1905.4083587  -1965.35910243]
 [-1916.14438894 -1916.14438894 -1957.71735387]
 [-1919.66089674 -1919.66089674 -1957.7196805 ]
 [-1923.01517067 -1923.01517067 -1952.52875907]
 [           nan            nan            nan]]
pca_f 4
(87, 1805375)
ll  for production factors 4
[[-1840.26221071 -1840.26221071 -2015.85910639]
 [-1844.622829   -1844.622829   -2011.39022323]
 [-1848.97024984 -1848.97024984 -2007.06813557]
 [-1851.42880072 -1851.42880072 -2002.58899429]
 [-1864.28300515 -1864.28300515 -1986.89383575]
 [-1875.03616351 -1875.03616351 -1979.01176238]
 [-1903.67565435 -1903.67565435 -1966.59635997]
 [-1914.49546477 -1914.49546477 -1958.97794441]
 [

/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 87 but corresponding boolean dimension is 42



ll   for only important factors 
[[-1841.85854171 -1841.85854171 -2014.95356235]
 [-1846.24250635 -1846.24250635 -2010.44660848]
 [-1850.61169653 -1850.61169653 -2006.09528517]
 [-1853.01965937 -1853.01965937 -2001.45070514]
 [-1865.87988708 -1865.87988708 -1985.77501312]
 [-1876.75134569 -1876.75134569 -1977.67128376]
 [-1905.40823489 -1905.40823489 -1965.37901572]
 [-1916.14425534 -1916.14425534 -1957.73235727]
 [-1919.66075166 -1919.66075166 -1957.7338951 ]
 [-1923.01501694 -1923.01501694 -1952.53638278]
 [           nan            nan            nan]]
pca_f 5
(86, 1805375)
ll  for production factors 5
[[-1840.12300078 -1840.12300078 -2016.08655747]
 [-1844.51944252 -1844.51944252 -2011.58578997]
 [-1848.93675111 -1848.93675111 -2007.18149549]
 [-1851.44099314 -1851.44099314 -2002.54978325]
 [-1864.43023818 -1864.43023818 -1986.82741461]
 [-1875.11157842 -1875.11157842 -1979.06476439]
 [-1903.96511875 -1903.96511875 -1966.98881224]
 [-1914.75078585 -1914.75078585 -1958.97264913]
 [

/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 86 but corresponding boolean dimension is 41



ll   for only important factors 
[[-1841.82907205 -1841.82907205 -2014.94648639]
 [-1846.21117918 -1846.21117918 -2010.44500547]
 [-1850.57994379 -1850.57994379 -2006.09640883]
 [-1852.98703587 -1852.98703587 -2001.46228874]
 [-1865.84306342 -1865.84306342 -1985.82797626]
 [-1876.70720313 -1876.70720313 -1977.75596621]
 [-1905.36618572 -1905.36618572 -1965.47353169]
 [-1916.10809279 -1916.10809279 -1957.81421645]
 [-1919.62379896 -1919.62379896 -1957.83137159]
 [-1922.97538525 -1922.97538525 -1952.63528006]
 [           nan            nan            nan]]
pca_f 6
(85, 1805375)
ll  for production factors 6
[[-1840.35832013 -1840.35832013 -2016.32808119]
 [-1844.71205212 -1844.71205212 -2011.91534926]
 [-1849.0764369  -1849.0764369  -2007.46400341]
 [-1851.49064735 -1851.49064735 -2003.11934017]
 [-1864.28679455 -1864.28679455 -1987.32971561]
 [-1875.15927866 -1875.15927866 -1978.83826167]
 [-1903.47294882 -1903.47294882 -1967.32421007]
 [-1914.21679259 -1914.21679259 -1959.65327807]
 [

/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 85 but corresponding boolean dimension is 40



ll   for only important factors 
[[-1841.85843555 -1841.85843555 -2014.94347278]
 [-1846.24237719 -1846.24237719 -2010.43597698]
 [-1850.61156919 -1850.61156919 -2006.08437709]
 [-1853.01951822 -1853.01951822 -2001.43917455]
 [-1865.87970359 -1865.87970359 -1985.76106447]
 [-1876.75111946 -1876.75111946 -1977.65559486]
 [-1905.4078909  -1905.4078909  -1965.36252918]
 [-1916.14386228 -1916.14386228 -1957.71654535]
 [-1919.66034554 -1919.66034554 -1957.71821293]
 [-1923.01450821 -1923.01450821 -1952.52412842]
 [           nan            nan            nan]]
pca_f 7
(84, 1805375)
ll  for production factors 7
[[-1840.15896569 -1840.15896569 -2014.46320771]
 [-1844.4960167  -1844.4960167  -2010.01398299]
 [-1848.8593976  -1848.8593976  -2005.60220637]
 [-1851.27631108 -1851.27631108 -2000.97831197]
 [-1864.22714695 -1864.22714695 -1985.37894751]
 [-1875.17890241 -1875.17890241 -1977.38177412]
 [-1903.73459692 -1903.73459692 -1965.03111723]
 [-1914.56439826 -1914.56439826 -1957.49179667]
 [

/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 84 but corresponding boolean dimension is 39



ll   for only important factors 
[[-1841.82922646 -1841.82922646 -2014.94734221]
 [-1846.21134524 -1846.21134524 -2010.44583329]
 [-1850.58011453 -1850.58011453 -2006.09725544]
 [-1852.9871969  -1852.9871969  -2001.4630034 ]
 [-1865.84324505 -1865.84324505 -1985.82888214]
 [-1876.70741848 -1876.70741848 -1977.75761067]
 [-1905.36639538 -1905.36639538 -1965.47613054]
 [-1916.10836138 -1916.10836138 -1957.81675717]
 [-1919.6240562  -1919.6240562  -1957.83331188]
 [-1922.97573416 -1922.97573416 -1952.63642457]
 [           nan            nan            nan]]
pca_f 8
(83, 1805375)
ll  for production factors 8
[[-1840.20306192 -1840.20306192 -2014.65276998]
 [-1844.53621347 -1844.53621347 -2010.15613504]
 [-1848.86011821 -1848.86011821 -2005.97352926]
 [-1851.25449841 -1851.25449841 -2001.30725705]
 [-1864.07434204 -1864.07434204 -1985.7143878 ]
 [-1874.76811311 -1874.76811311 -1977.48402613]
 [-1903.43307952 -1903.43307952 -1965.19072955]
 [-1914.0893169  -1914.0893169  -1957.55787377]
 [

/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 83 but corresponding boolean dimension is 38



ll   for only important factors 
[[-1841.82908088 -1841.82908088 -2014.8755019 ]
 [-1846.21117914 -1846.21117914 -2010.37382872]
 [-1850.57993977 -1850.57993977 -2006.02505592]
 [-1852.98702406 -1852.98702406 -2001.39106329]
 [-1865.8430351  -1865.8430351  -1985.75888712]
 [-1876.70714693 -1876.70714693 -1977.68788045]
 [-1905.36600579 -1905.36600579 -1965.41463467]
 [-1916.10785688 -1916.10785688 -1957.76984183]
 [-1919.62355586 -1919.62355586 -1957.78988663]
 [-1922.9750842  -1922.9750842  -1952.61062592]
 [           nan            nan            nan]]
pca_f 9
(82, 1805375)
ll  for production factors 9
[[-1840.39423133 -1840.39423133 -2015.7567764 ]
 [-1844.75599721 -1844.75599721 -2011.25197861]
 [-1849.10203367 -1849.10203367 -2006.98383343]
 [-1851.47248862 -1851.47248862 -2002.44109769]
 [-1864.34500986 -1864.34500986 -1987.01320025]
 [-1875.09561349 -1875.09561349 -1979.08774846]
 [-1903.84622602 -1903.84622602 -1966.94956053]
 [-1914.42875095 -1914.42875095 -1959.43359954]
 [

/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 82 but corresponding boolean dimension is 37



ll   for only important factors 
[[-1841.85860808 -1841.85860808 -2014.95025719]
 [-1846.24256926 -1846.24256926 -2010.44205446]
 [-1850.61176661 -1850.61176661 -2006.0901902 ]
 [-1853.01973699 -1853.01973699 -2001.44494271]
 [-1865.87996251 -1865.87996251 -1985.7639055 ]
 [-1876.75142383 -1876.75142383 -1977.65764341]
 [-1905.40831294 -1905.40831294 -1965.36248051]
 [-1916.14429961 -1916.14429961 -1957.71647366]
 [-1919.6608016  -1919.6608016  -1957.71774959]
 [-1923.01501741 -1923.01501741 -1952.52356083]
 [           nan            nan            nan]]
pca_f 10
(81, 1805375)
ll  for production factors 10
[[-1840.80075405 -1840.80075405 -2015.84678077]
 [-1845.1720776  -1845.1720776  -2011.43605973]
 [-1849.48819927 -1849.48819927 -2007.16469408]
 [-1851.88116426 -1851.88116426 -2002.42092069]
 [-1864.7094113  -1864.7094113  -1986.76026524]
 [-1875.47638393 -1875.47638393 -1978.63688702]
 [-1904.217161   -1904.217161   -1966.22300997]
 [-1914.97681781 -1914.97681781 -1958.4466384 ]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 81 but corresponding boolean dimension is 36



ll   for only important factors 
[[-1841.82916305 -1841.82916305 -2014.93663148]
 [-1846.21127288 -1846.21127288 -2010.43461604]
 [-1850.5800401  -1850.5800401  -2006.08584189]
 [-1852.98713802 -1852.98713802 -2001.45159669]
 [-1865.84316926 -1865.84316926 -1985.81544348]
 [-1876.70732414 -1876.70732414 -1977.7425819 ]
 [-1905.36629751 -1905.36629751 -1965.46074806]
 [-1916.10817244 -1916.10817244 -1957.80440459]
 [-1919.62388625 -1919.62388625 -1957.82150265]
 [-1922.97546452 -1922.97546452 -1952.62892581]
 [           nan            nan            nan]]
pca_f 11
(80, 1805375)
ll  for production factors 11
[[-1840.24972902 -1840.24972902 -2016.2603426 ]
 [-1844.58442352 -1844.58442352 -2011.72972992]
 [-1848.9230541  -1848.9230541  -2007.42860044]
 [-1851.35701567 -1851.35701567 -2002.73070758]
 [-1864.27086376 -1864.27086376 -1986.92147382]
 [-1874.95130848 -1874.95130848 -1979.28553488]
 [-1903.54579594 -1903.54579594 -1967.3796282 ]
 [-1914.49251654 -1914.49251654 -1959.54973836]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 80 but corresponding boolean dimension is 35



ll   for only important factors 
[[-1841.82935751 -1841.82935751 -2014.96010722]
 [-1846.21148654 -1846.21148654 -2010.45850441]
 [-1850.5802601  -1850.5802601  -2006.10947104]
 [-1852.98737334 -1852.98737334 -2001.47466305]
 [-1865.84345647 -1865.84345647 -1985.83857271]
 [-1876.70768148 -1876.70768148 -1977.76623006]
 [-1905.36680603 -1905.36680603 -1965.48249577]
 [-1916.10874246 -1916.10874246 -1957.82265987]
 [-1919.62446602 -1919.62446602 -1957.83897058]
 [-1922.97615834 -1922.97615834 -1952.64170477]
 [           nan            nan            nan]]
pca_f 12
(79, 1805375)
ll  for production factors 12
[[-1839.44558144 -1839.44558144 -2015.38125304]
 [-1843.91765032 -1843.91765032 -2010.98553896]
 [-1848.25516219 -1848.25516219 -2006.72521475]
 [-1850.61582685 -1850.61582685 -2002.20197919]
 [-1863.5602868  -1863.5602868  -1986.67875115]
 [-1874.42486659 -1874.42486659 -1978.55809652]
 [-1902.77386196 -1902.77386196 -1966.70044432]
 [-1913.37438432 -1913.37438432 -1958.86703469]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 79 but corresponding boolean dimension is 34



ll   for only important factors 
[[-1841.85859121 -1841.85859121 -2014.9172884 ]
 [-1846.24254144 -1846.24254144 -2010.40927427]
 [-1850.61173703 -1850.61173703 -2006.05720672]
 [-1853.01970037 -1853.01970037 -2001.4117932 ]
 [-1865.87989544 -1865.87989544 -1985.73432469]
 [-1876.75133136 -1876.75133136 -1977.63010386]
 [-1905.40813707 -1905.40813707 -1965.34184494]
 [-1916.14412907 -1916.14412907 -1957.70292511]
 [-1919.66062697 -1919.66062697 -1957.70580596]
 [-1923.01481713 -1923.01481713 -1952.51842664]
 [           nan            nan            nan]]
pca_f 13
(78, 1805375)
ll  for production factors 13
[[-1840.60074474 -1840.60074474 -2015.85960132]
 [-1844.95431536 -1844.95431536 -2011.31892186]
 [-1849.28890277 -1849.28890277 -2006.99304826]
 [-1851.56211597 -1851.56211597 -2002.39471033]
 [-1864.51523494 -1864.51523494 -1986.6996231 ]
 [-1875.22261719 -1875.22261719 -1978.70877338]
 [-1903.76672594 -1903.76672594 -1966.42542581]
 [-1914.43282362 -1914.43282362 -1958.82189443]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 78 but corresponding boolean dimension is 33



ll   for only important factors 
[[-1841.85858915 -1841.85858915 -2014.89604208]
 [-1846.24254284 -1846.24254284 -2010.38822692]
 [-1850.6117324  -1850.6117324  -2006.03639178]
 [-1853.01969307 -1853.01969307 -2001.39166993]
 [-1865.87990273 -1865.87990273 -1985.71631802]
 [-1876.75132657 -1876.75132657 -1977.61293447]
 [-1905.40814175 -1905.40814175 -1965.32761597]
 [-1916.14410464 -1916.14410464 -1957.69203878]
 [-1919.66060541 -1919.66060541 -1957.69580291]
 [-1923.01479403 -1923.01479403 -1952.51113585]
 [           nan            nan            nan]]
pca_f 14
(77, 1805375)
ll  for production factors 14
[[-1840.61990871 -1840.61990871 -2015.11182106]
 [-1844.92062577 -1844.92062577 -2010.59769775]
 [-1849.14811812 -1849.14811812 -2006.24757638]
 [-1851.58894033 -1851.58894033 -2001.58980863]
 [-1864.32533466 -1864.32533466 -1986.2229179 ]
 [-1875.16970495 -1875.16970495 -1978.26131024]
 [-1903.74205976 -1903.74205976 -1965.81712526]
 [-1914.58090974 -1914.58090974 -1958.13905575]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 77 but corresponding boolean dimension is 32



ll   for only important factors 
[[-1841.85840475 -1841.85840475 -2014.9017495 ]
 [-1846.24235028 -1846.24235028 -2010.39439682]
 [-1850.61153277 -1850.61153277 -2006.04240918]
 [-1853.01947763 -1853.01947763 -2001.3974652 ]
 [-1865.87966332 -1865.87966332 -1985.72279922]
 [-1876.75105656 -1876.75105656 -1977.61955161]
 [-1905.40781189 -1905.40781189 -1965.33328708]
 [-1916.14378018 -1916.14378018 -1957.69627295]
 [-1919.66027404 -1919.66027404 -1957.70000733]
 [-1923.01441314 -1923.01441314 -1952.51453283]
 [           nan            nan            nan]]
pca_f 15
(76, 1805375)
ll  for production factors 15
[[-1840.61624024 -1840.61624024 -2015.73564702]
 [-1845.08273299 -1845.08273299 -2011.26031993]
 [-1849.49496985 -1849.49496985 -2007.03349758]
 [-1851.83773365 -1851.83773365 -2002.39282218]
 [-1864.63228399 -1864.63228399 -1986.82765782]
 [-1875.42670846 -1875.42670846 -1978.8283107 ]
 [-1904.03084003 -1904.03084003 -1966.89213917]
 [-1914.63012469 -1914.63012469 -1959.42483135]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 76 but corresponding boolean dimension is 31



ll   for only important factors 
[[-1841.82921548 -1841.82921548 -2014.90795336]
 [-1846.21132943 -1846.21132943 -2010.40660954]
 [-1850.58009084 -1850.58009084 -2006.05778236]
 [-1852.98718291 -1852.98718291 -2001.42390509]
 [-1865.84323483 -1865.84323483 -1985.79180568]
 [-1876.70739239 -1876.70739239 -1977.72119058]
 [-1905.36638908 -1905.36638908 -1965.44502357]
 [-1916.10828382 -1916.10828382 -1957.79403885]
 [-1919.62400135 -1919.62400135 -1957.81232189]
 [-1922.97560553 -1922.97560553 -1952.62436285]
 [           nan            nan            nan]]
pca_f 16
(75, 1805375)
ll  for production factors 16
[[-1840.05631899 -1840.05631899 -2015.27184477]
 [-1844.39178067 -1844.39178067 -2010.83632489]
 [-1848.7104955  -1848.7104955  -2006.49146644]
 [-1851.14275188 -1851.14275188 -2001.83314609]
 [-1863.94106338 -1863.94106338 -1986.22812302]
 [-1874.89904099 -1874.89904099 -1978.07243352]
 [-1903.57679255 -1903.57679255 -1965.5684555 ]
 [-1914.16152931 -1914.16152931 -1957.95260818]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 75 but corresponding boolean dimension is 30



ll   for only important factors 
[[-1841.82915413 -1841.82915413 -2014.88008779]
 [-1846.21125533 -1846.21125533 -2010.37833048]
 [-1850.58002031 -1850.58002031 -2006.02970702]
 [-1852.98709884 -1852.98709884 -2001.39614676]
 [-1865.84310955 -1865.84310955 -1985.76642189]
 [-1876.70723158 -1876.70723158 -1977.69756885]
 [-1905.36612485 -1905.36612485 -1965.42609746]
 [-1916.10801076 -1916.10801076 -1957.7806419 ]
 [-1919.62370869 -1919.62370869 -1957.80057263]
 [-1922.97528645 -1922.97528645 -1952.61887779]
 [           nan            nan            nan]]
pca_f 17
(74, 1805375)
ll  for production factors 17
[[-1840.80788704 -1840.80788704 -2015.5023089 ]
 [-1845.15395689 -1845.15395689 -2010.97815325]
 [-1849.49879282 -1849.49879282 -2006.64807414]
 [-1851.97678554 -1851.97678554 -2002.01113416]
 [-1864.73519288 -1864.73519288 -1986.60835081]
 [-1875.59640123 -1875.59640123 -1978.66312354]
 [-1904.12806189 -1904.12806189 -1966.57646848]
 [-1914.90238274 -1914.90238274 -1958.94468904]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 74 but corresponding boolean dimension is 29



ll   for only important factors 
[[-1841.85875736 -1841.85875736 -2014.92324826]
 [-1846.24272159 -1846.24272159 -2010.41553486]
 [-1850.61192173 -1850.61192173 -2006.06367914]
 [-1853.01989319 -1853.01989319 -2001.41843322]
 [-1865.88010545 -1865.88010545 -1985.74185592]
 [-1876.75158814 -1876.75158814 -1977.63821675]
 [-1905.40851028 -1905.40851028 -1965.34958512]
 [-1916.14449608 -1916.14449608 -1957.71065662]
 [-1919.66100867 -1919.66100867 -1957.71328267]
 [-1923.01524438 -1923.01524438 -1952.52502869]
 [           nan            nan            nan]]
pca_f 18
(73, 1805375)
ll  for production factors 18
[[-1840.31517346 -1840.31517346 -2016.69834173]
 [-1844.73143532 -1844.73143532 -2011.99571244]
 [-1849.08334463 -1849.08334463 -2007.70275749]
 [-1851.5023394  -1851.5023394  -2003.08897853]
 [-1864.33256643 -1864.33256643 -1987.64570394]
 [-1874.97074722 -1874.97074722 -1979.78450051]
 [-1903.6691601  -1903.6691601  -1967.90167163]
 [-1914.40741202 -1914.40741202 -1960.21446025]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 73 but corresponding boolean dimension is 28



ll   for only important factors 
[[-1841.82898859 -1841.82898859 -2014.89160014]
 [-1846.2110824  -1846.2110824  -2010.3904748 ]
 [-1850.57984172 -1850.57984172 -2006.04180344]
 [-1852.98690932 -1852.98690932 -2001.40843577]
 [-1865.84291211 -1865.84291211 -1985.779492  ]
 [-1876.70701521 -1876.70701521 -1977.71015718]
 [-1905.36583701 -1905.36583701 -1965.43759516]
 [-1916.10773739 -1916.10773739 -1957.7891141 ]
 [-1919.62343495 -1919.62343495 -1957.80840438]
 [-1922.9749851  -1922.9749851  -1952.62357468]
 [           nan            nan            nan]]
pca_f 19
(72, 1805375)
ll  for production factors 19
[[-1840.71567033 -1840.71567033 -2015.52267977]
 [-1845.10596789 -1845.10596789 -2010.89869503]
 [-1849.45435354 -1849.45435354 -2006.52799026]
 [-1851.91727945 -1851.91727945 -2001.90695703]
 [-1864.7308439  -1864.7308439  -1986.31166896]
 [-1875.58828317 -1875.58828317 -1978.16196376]
 [-1904.28049343 -1904.28049343 -1965.55752847]
 [-1915.1184945  -1915.1184945  -1957.85309917]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 72 but corresponding boolean dimension is 27



ll   for only important factors 
[[-1841.85836208 -1841.85836208 -2014.95027957]
 [-1846.24231833 -1846.24231833 -2010.44326836]
 [-1850.61150757 -1850.61150757 -2006.09172559]
 [-1853.01944157 -1853.01944157 -2001.44682266]
 [-1865.87962374 -1865.87962374 -1985.77115378]
 [-1876.75103817 -1876.75103817 -1977.66707315]
 [-1905.40778179 -1905.40778179 -1965.37529727]
 [-1916.14382759 -1916.14382759 -1957.7285424 ]
 [-1919.66030105 -1919.66030105 -1957.730042  ]
 [-1923.01451208 -1923.01451208 -1952.53370522]
 [           nan            nan            nan]]
pca_f 20
(71, 1805375)
ll  for production factors 20
[[-1840.6924786  -1840.6924786  -2015.11322308]
 [-1845.08223986 -1845.08223986 -2010.55853339]
 [-1849.46745009 -1849.46745009 -2006.13686055]
 [-1851.84410944 -1851.84410944 -2001.60512502]
 [-1864.80706886 -1864.80706886 -1985.89967092]
 [-1875.79622204 -1875.79622204 -1977.9127641 ]
 [-1904.44657845 -1904.44657845 -1965.80101075]
 [-1915.21066016 -1915.21066016 -1958.15061638]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 71 but corresponding boolean dimension is 26



ll   for only important factors 
[[-1841.85841522 -1841.85841522 -2014.9505896 ]
 [-1846.24236837 -1846.24236837 -2010.44346038]
 [-1850.61155631 -1850.61155631 -2006.09209066]
 [-1853.01949352 -1853.01949352 -2001.44719078]
 [-1865.8796854  -1865.8796854  -1985.77156243]
 [-1876.75109711 -1876.75109711 -1977.66797287]
 [-1905.40785776 -1905.40785776 -1965.37652848]
 [-1916.14392542 -1916.14392542 -1957.729672  ]
 [-1919.66039581 -1919.66039581 -1957.73125853]
 [-1923.01464421 -1923.01464421 -1952.53414114]
 [           nan            nan            nan]]
pca_f 21
(70, 1805375)
ll  for production factors 21
[[-1841.34814579 -1841.34814579 -2014.51751318]
 [-1845.71469847 -1845.71469847 -2010.02007894]
 [-1850.08820859 -1850.08820859 -2005.74162286]
 [-1852.4859421  -1852.4859421  -2001.01761047]
 [-1865.39617103 -1865.39617103 -1985.30410571]
 [-1876.27065544 -1876.27065544 -1977.14527655]
 [-1904.83314117 -1904.83314117 -1965.00673176]
 [-1915.46416114 -1915.46416114 -1957.32871195]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 70 but corresponding boolean dimension is 25



ll   for only important factors 
[[-1841.85879058 -1841.85879058 -2014.97650514]
 [-1846.24277362 -1846.24277362 -2010.46906523]
 [-1850.61196987 -1850.61196987 -2006.11715854]
 [-1853.01995795 -1853.01995795 -2001.47177094]
 [-1865.88023162 -1865.88023162 -1985.79229781]
 [-1876.75176475 -1876.75176475 -1977.68667031]
 [-1905.40881178 -1905.40881178 -1965.39091481]
 [-1916.1448208  -1916.1448208  -1957.7413721 ]
 [-1919.66134026 -1919.66134026 -1957.74158857]
 [-1923.01563969 -1923.01563969 -1952.5410817 ]
 [           nan            nan            nan]]
pca_f 22
(69, 1805375)
ll  for production factors 22
[[-1840.63152226 -1840.63152226 -2016.2017937 ]
 [-1845.00355346 -1845.00355346 -2011.80202869]
 [-1849.3359907  -1849.3359907  -2007.50040097]
 [-1851.7392639  -1851.7392639  -2002.91718409]
 [-1864.54144755 -1864.54144755 -1987.43793718]
 [-1875.35570684 -1875.35570684 -1979.56167842]
 [-1904.07169097 -1904.07169097 -1967.14004606]
 [-1914.75781249 -1914.75781249 -1959.33894888]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 69 but corresponding boolean dimension is 24



ll   for only important factors 
[[-1841.85885368 -1841.85885368 -2014.92870281]
 [-1846.24283329 -1846.24283329 -2010.42084153]
 [-1850.61203118 -1850.61203118 -2006.06878751]
 [-1853.02001603 -1853.02001603 -2001.4234593 ]
 [-1865.88027134 -1865.88027134 -1985.74576745]
 [-1876.75178731 -1876.75178731 -1977.64143894]
 [-1905.40876601 -1905.40876601 -1965.35205967]
 [-1916.1447649  -1916.1447649  -1957.71226316]
 [-1919.66128268 -1919.66128268 -1957.71447733]
 [-1923.01556441 -1923.01556441 -1952.52504812]
 [           nan            nan            nan]]
pca_f 23
(68, 1805375)
ll  for production factors 23
[[-1840.87898256 -1840.87898256 -2015.49466829]
 [-1845.19617075 -1845.19617075 -2011.01233226]
 [-1849.58813672 -1849.58813672 -2006.67188859]
 [-1852.02357907 -1852.02357907 -2001.99429396]
 [-1864.82381955 -1864.82381955 -1986.63025748]
 [-1875.65539168 -1875.65539168 -1978.68584462]
 [-1904.38939564 -1904.38939564 -1966.28233601]
 [-1914.9606851  -1914.9606851  -1958.67207671]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 68 but corresponding boolean dimension is 23



ll   for only important factors 
[[-1841.85875528 -1841.85875528 -2014.93146271]
 [-1846.24272724 -1846.24272724 -2010.42374753]
 [-1850.61191972 -1850.61191972 -2006.07159359]
 [-1853.01988977 -1853.01988977 -2001.4261751 ]
 [-1865.88013988 -1865.88013988 -1985.74854684]
 [-1876.75163138 -1876.75163138 -1977.64414499]
 [-1905.40857045 -1905.40857045 -1965.35413168]
 [-1916.14456714 -1916.14456714 -1957.71249941]
 [-1919.66107787 -1919.66107787 -1957.7144409 ]
 [-1923.01534921 -1923.01534921 -1952.52380701]
 [           nan            nan            nan]]
pca_f 24
(67, 1805375)
ll  for production factors 24
[[-1841.29773118 -1841.29773118 -2015.16833009]
 [-1845.66666262 -1845.66666262 -2010.7777144 ]
 [-1850.04043422 -1850.04043422 -2006.36404355]
 [-1852.46609589 -1852.46609589 -2001.65187311]
 [-1865.18821705 -1865.18821705 -1986.18171294]
 [-1875.91136483 -1875.91136483 -1978.22056823]
 [-1904.56495612 -1904.56495612 -1965.83012876]
 [-1915.26603303 -1915.26603303 -1958.06555212]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 67 but corresponding boolean dimension is 22



ll   for only important factors 
[[-1841.85888929 -1841.85888929 -2014.91856381]
 [-1846.24286909 -1846.24286909 -2010.4106721 ]
 [-1850.6120654  -1850.6120654  -2006.05854603]
 [-1853.02005412 -1853.02005412 -2001.41313107]
 [-1865.88031546 -1865.88031546 -1985.73514271]
 [-1876.75183801 -1876.75183801 -1977.63063797]
 [-1905.40882326 -1905.40882326 -1965.34214701]
 [-1916.14479879 -1916.14479879 -1957.70453217]
 [-1919.66131858 -1919.66131858 -1957.70719485]
 [-1923.01559309 -1923.01559309 -1952.52019787]
 [           nan            nan            nan]]
pca_f 25
(66, 1805375)
ll  for production factors 25
[[-1840.89651068 -1840.89651068 -2015.36932178]
 [-1845.29508966 -1845.29508966 -2010.86758016]
 [-1849.68510534 -1849.68510534 -2006.51506206]
 [-1852.10985568 -1852.10985568 -2001.75674313]
 [-1864.82879481 -1864.82879481 -1986.32589415]
 [-1875.63098664 -1875.63098664 -1978.45188616]
 [-1904.28703919 -1904.28703919 -1966.00099125]
 [-1914.94959634 -1914.94959634 -1958.54129905]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 66 but corresponding boolean dimension is 21



ll   for only important factors 
[[-1841.85856408 -1841.85856408 -2014.96504231]
 [-1846.2425263  -1846.2425263  -2010.45782162]
 [-1850.6117164  -1850.6117164  -2006.10601107]
 [-1853.01968153 -1853.01968153 -2001.46084829]
 [-1865.8799131  -1865.8799131  -1985.78301506]
 [-1876.75138086 -1876.75138086 -1977.67782623]
 [-1905.40828011 -1905.40828011 -1965.3836814 ]
 [-1916.14428004 -1916.14428004 -1957.73478979]
 [-1919.66078276 -1919.66078276 -1957.73557777]
 [-1923.0150119  -1923.0150119  -1952.53622853]
 [           nan            nan            nan]]
pca_f 26
(65, 1805375)
ll  for production factors 26
[[-1841.07764018 -1841.07764018 -2016.10670582]
 [-1845.42348256 -1845.42348256 -2011.63135657]
 [-1849.77168828 -1849.77168828 -2007.35772614]
 [-1852.15261075 -1852.15261075 -2002.67675828]
 [-1864.98826817 -1864.98826817 -1986.88543357]
 [-1875.88663158 -1875.88663158 -1978.65282155]
 [-1904.45317288 -1904.45317288 -1966.31224586]
 [-1915.16614472 -1915.16614472 -1958.61201374]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 65 but corresponding boolean dimension is 20



ll   for only important factors 
[[-1841.85872411 -1841.85872411 -2014.97090033]
 [-1846.24269096 -1846.24269096 -2010.46337487]
 [-1850.61189032 -1850.61189032 -2006.11136037]
 [-1853.01986257 -1853.01986257 -2001.46575704]
 [-1865.88009856 -1865.88009856 -1985.78648638]
 [-1876.75160645 -1876.75160645 -1977.68098958]
 [-1905.40856929 -1905.40856929 -1965.38587475]
 [-1916.14459261 -1916.14459261 -1957.7370661 ]
 [-1919.66110319 -1919.66110319 -1957.73732359]
 [-1923.01538379 -1923.01538379 -1952.53843455]
 [           nan            nan            nan]]
pca_f 27
(64, 1805375)
ll  for production factors 27
[[-1841.30243232 -1841.30243232 -2014.83318786]
 [-1845.68155795 -1845.68155795 -2010.25571705]
 [-1850.06317193 -1850.06317193 -2005.86452811]
 [-1852.41640057 -1852.41640057 -2001.25352019]
 [-1865.22405539 -1865.22405539 -1985.55204385]
 [-1875.96724651 -1875.96724651 -1977.56486074]
 [-1904.70830758 -1904.70830758 -1965.25824255]
 [-1915.45127444 -1915.45127444 -1957.58960562]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 64 but corresponding boolean dimension is 19



ll   for only important factors 
[[-1841.85868156 -1841.85868156 -2014.9321938 ]
 [-1846.24264527 -1846.24264527 -2010.42453252]
 [-1850.61183837 -1850.61183837 -2006.07230719]
 [-1853.01981156 -1853.01981156 -2001.4268219 ]
 [-1865.88003514 -1865.88003514 -1985.74919739]
 [-1876.75150871 -1876.75150871 -1977.64445033]
 [-1905.40842218 -1905.40842218 -1965.35432472]
 [-1916.14439786 -1916.14439786 -1957.71247355]
 [-1919.66091006 -1919.66091006 -1957.71460942]
 [-1923.01512584 -1923.01512584 -1952.52358401]
 [           nan            nan            nan]]
pca_f 28
(63, 1805375)
ll  for production factors 28
[[-1841.35342381 -1841.35342381 -2015.43696711]
 [-1845.73273984 -1845.73273984 -2011.00536426]
 [-1850.08187807 -1850.08187807 -2006.6438929 ]
 [-1852.4535304  -1852.4535304  -2001.97771259]
 [-1865.26698509 -1865.26698509 -1986.47136309]
 [-1876.08146505 -1876.08146505 -1978.49010379]
 [-1904.72068046 -1904.72068046 -1966.55271368]
 [-1915.36087887 -1915.36087887 -1959.11939459]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 63 but corresponding boolean dimension is 18



ll   for only important factors 
[[-1841.82925999 -1841.82925999 -2014.91584181]
 [-1846.21137343 -1846.21137343 -2010.41444475]
 [-1850.58013828 -1850.58013828 -2006.06556301]
 [-1852.98722941 -1852.98722941 -2001.43152883]
 [-1865.84328628 -1865.84328628 -1985.79913031]
 [-1876.70746213 -1876.70746213 -1977.72864415]
 [-1905.3664825  -1905.3664825  -1965.45171879]
 [-1916.10839125 -1916.10839125 -1957.79973775]
 [-1919.62410701 -1919.62410701 -1957.81768554]
 [-1922.97574808 -1922.97574808 -1952.6288125 ]
 [           nan            nan            nan]]
pca_f 29
(62, 1805375)
ll  for production factors 29
[[-1840.72419722 -1840.72419722 -2016.21816174]
 [-1845.1515623  -1845.1515623  -2011.64282272]
 [-1849.47992197 -1849.47992197 -2007.31704496]
 [-1851.87692167 -1851.87692167 -2002.67784481]
 [-1864.68801608 -1864.68801608 -1987.08534115]
 [-1875.55604361 -1875.55604361 -1978.95291752]
 [-1904.32610101 -1904.32610101 -1966.53554329]
 [-1915.06066783 -1915.06066783 -1958.85134005]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 62 but corresponding boolean dimension is 17



ll   for only important factors 
[[-1841.82900928 -1841.82900928 -2014.93757822]
 [-1846.21111578 -1846.21111578 -2010.43684184]
 [-1850.57987669 -1850.57987669 -2006.08855371]
 [-1852.98693762 -1852.98693762 -2001.45499893]
 [-1865.84295719 -1865.84295719 -1985.82443618]
 [-1876.70708054 -1876.70708054 -1977.75432985]
 [-1905.3659362  -1905.3659362  -1965.47555174]
 [-1916.10789541 -1916.10789541 -1957.81697031]
 [-1919.62357328 -1919.62357328 -1957.83419076]
 [-1922.97519702 -1922.97519702 -1952.63775395]
 [           nan            nan            nan]]
pca_f 30
(61, 1805375)
ll  for production factors 30
[[-1841.20019056 -1841.20019056 -2016.43856486]
 [-1845.55070992 -1845.55070992 -2011.99905337]
 [-1849.93556251 -1849.93556251 -2007.60519787]
 [-1852.30070464 -1852.30070464 -2003.04099873]
 [-1865.19300367 -1865.19300367 -1987.37274837]
 [-1876.08595821 -1876.08595821 -1979.30122789]
 [-1904.68973319 -1904.68973319 -1966.98511056]
 [-1915.37916554 -1915.37916554 -1959.47929079]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 61 but corresponding boolean dimension is 16



ll   for only important factors 
[[-1841.85881236 -1841.85881236 -2014.97909035]
 [-1846.24279226 -1846.24279226 -2010.47169794]
 [-1850.61199147 -1850.61199147 -2006.11973399]
 [-1853.01997539 -1853.01997539 -2001.474147  ]
 [-1865.88024587 -1865.88024587 -1985.79444021]
 [-1876.75178664 -1876.75178664 -1977.68869465]
 [-1905.4088018  -1905.4088018  -1965.39247394]
 [-1916.14481116 -1916.14481116 -1957.74202014]
 [-1919.66132843 -1919.66132843 -1957.74182483]
 [-1923.01563178 -1923.01563178 -1952.54072689]
 [           nan            nan            nan]]
pca_f 31
(60, 1805375)
ll  for production factors 31
[[-1841.31107767 -1841.31107767 -2015.26770788]
 [-1845.68014939 -1845.68014939 -2010.76920227]
 [-1850.02612464 -1850.02612464 -2006.44543833]
 [-1852.46653805 -1852.46653805 -2001.7881202 ]
 [-1865.16645779 -1865.16645779 -1986.2115914 ]
 [-1875.99413757 -1875.99413757 -1977.98749204]
 [-1904.6599208  -1904.6599208  -1965.66793826]
 [-1915.33726519 -1915.33726519 -1957.9861872 ]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 60 but corresponding boolean dimension is 15



ll   for only important factors 
[[-1841.82915927 -1841.82915927 -2014.93760625]
 [-1846.21127589 -1846.21127589 -2010.43645682]
 [-1850.5800401  -1850.5800401  -2006.08786423]
 [-1852.98713329 -1852.98713329 -2001.45417852]
 [-1865.84317537 -1865.84317537 -1985.82195816]
 [-1876.70733959 -1876.70733959 -1977.751106  ]
 [-1905.36634907 -1905.36634907 -1965.47190613]
 [-1916.10826623 -1916.10826623 -1957.81593957]
 [-1919.62398357 -1919.62398357 -1957.83317192]
 [-1922.97560548 -1922.97560548 -1952.63826831]
 [           nan            nan            nan]]
pca_f 32
(59, 1805375)
ll  for production factors 32
[[-1841.45505861 -1841.45505861 -2015.63619061]
 [-1845.88015243 -1845.88015243 -2011.01674815]
 [-1850.29696671 -1850.29696671 -2006.58468549]
 [-1852.75475286 -1852.75475286 -2001.88126233]
 [-1865.6136626  -1865.6136626  -1986.16990805]
 [-1876.432997   -1876.432997   -1978.19564621]
 [-1905.03499997 -1905.03499997 -1965.95406379]
 [-1915.83066068 -1915.83066068 -1958.12662099]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 59 but corresponding boolean dimension is 14



ll   for only important factors 
[[-1841.85856675 -1841.85856675 -2014.92794741]
 [-1846.24252939 -1846.24252939 -2010.42044822]
 [-1850.61172084 -1850.61172084 -2006.06841491]
 [-1853.01967219 -1853.01967219 -2001.4229682 ]
 [-1865.87987033 -1865.87987033 -1985.74633408]
 [-1876.75131254 -1876.75131254 -1977.64193922]
 [-1905.40811058 -1905.40811058 -1965.35256953]
 [-1916.14411246 -1916.14411246 -1957.71048998]
 [-1919.66060671 -1919.66060671 -1957.71283931]
 [-1923.014817   -1923.014817   -1952.52174515]
 [           nan            nan            nan]]
pca_f 33
(58, 1805375)
ll  for production factors 33
[[-1841.23920196 -1841.23920196 -2015.1813104 ]
 [-1845.58368271 -1845.58368271 -2010.76133142]
 [-1849.97715334 -1849.97715334 -2006.37702293]
 [-1852.39614672 -1852.39614672 -2001.70233067]
 [-1865.19046188 -1865.19046188 -1986.16548213]
 [-1875.99792631 -1875.99792631 -1978.11767875]
 [-1904.7515669  -1904.7515669  -1965.7693361 ]
 [-1915.56702625 -1915.56702625 -1958.03162527]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 58 but corresponding boolean dimension is 13



ll   for only important factors 
[[-1841.85859656 -1841.85859656 -2014.96054813]
 [-1846.24256071 -1846.24256071 -2010.45337927]
 [-1850.61175048 -1850.61175048 -2006.10167996]
 [-1853.01971216 -1853.01971216 -2001.45652595]
 [-1865.87994716 -1865.87994716 -1985.77920199]
 [-1876.75142089 -1876.75142089 -1977.67435855]
 [-1905.40830523 -1905.40830523 -1965.38080829]
 [-1916.14430777 -1916.14430777 -1957.73250252]
 [-1919.66080364 -1919.66080364 -1957.73325278]
 [-1923.01504957 -1923.01504957 -1952.53465843]
 [           nan            nan            nan]]
pca_f 34
(57, 1805375)
ll  for production factors 34
[[-1841.17284279 -1841.17284279 -2014.8570657 ]
 [-1845.56854091 -1845.56854091 -2010.34692874]
 [-1849.93860589 -1849.93860589 -2005.99550353]
 [-1852.3475329  -1852.3475329  -2001.4195155 ]
 [-1865.25155765 -1865.25155765 -1985.68436268]
 [-1876.06546857 -1876.06546857 -1977.44658511]
 [-1904.76710286 -1904.76710286 -1965.44135171]
 [-1915.45107657 -1915.45107657 -1957.79256846]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 57 but corresponding boolean dimension is 12



ll   for only important factors 
[[-1841.8589166  -1841.8589166  -2014.91662121]
 [-1846.24289457 -1846.24289457 -2010.40868821]
 [-1850.61209431 -1850.61209431 -2006.0564109 ]
 [-1853.02008128 -1853.02008128 -2001.41090464]
 [-1865.88033391 -1865.88033391 -1985.73305492]
 [-1876.75185476 -1876.75185476 -1977.62859516]
 [-1905.40882348 -1905.40882348 -1965.34039437]
 [-1916.14478259 -1916.14478259 -1957.702604  ]
 [-1919.66130277 -1919.66130277 -1957.70525442]
 [-1923.01557048 -1923.01557048 -1952.51833808]
 [           nan            nan            nan]]
pca_f 35
(56, 1805375)
ll  for production factors 35
[[-1841.41337698 -1841.41337698 -2014.67551239]
 [-1845.77594005 -1845.77594005 -2010.18566914]
 [-1850.14604479 -1850.14604479 -2005.84921793]
 [-1852.56808569 -1852.56808569 -2001.19944879]
 [-1865.49600999 -1865.49600999 -1985.62580512]
 [-1876.31493204 -1876.31493204 -1977.55454271]
 [-1904.96957251 -1904.96957251 -1965.39359396]
 [-1915.70832763 -1915.70832763 -1957.73621681]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 56 but corresponding boolean dimension is 11



ll   for only important factors 
[[-1841.85843662 -1841.85843662 -2014.95949586]
 [-1846.24239752 -1846.24239752 -2010.45247879]
 [-1850.61158549 -1850.61158549 -2006.10086137]
 [-1853.01952436 -1853.01952436 -2001.45570895]
 [-1865.87972581 -1865.87972581 -1985.77922221]
 [-1876.75115916 -1876.75115916 -1977.67468919]
 [-1905.40793531 -1905.40793531 -1965.38161236]
 [-1916.14397053 -1916.14397053 -1957.73280495]
 [-1919.66044725 -1919.66044725 -1957.73379314]
 [-1923.0146831  -1923.0146831  -1952.534845  ]
 [           nan            nan            nan]]
pca_f 36
(55, 1805375)
ll  for production factors 36
[[-1841.13063995 -1841.13063995 -2015.99512365]
 [-1845.45315831 -1845.45315831 -2011.5626265 ]
 [-1849.80679609 -1849.80679609 -2007.18856562]
 [-1852.17370755 -1852.17370755 -2002.61500253]
 [-1865.00528261 -1865.00528261 -1987.17936115]
 [-1875.84039031 -1875.84039031 -1979.13282547]
 [-1904.50870979 -1904.50870979 -1967.02983038]
 [-1915.26205659 -1915.26205659 -1959.31763122]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 55 but corresponding boolean dimension is 10



ll   for only important factors 
[[-1841.85884361 -1841.85884361 -2014.92544159]
 [-1846.24282089 -1846.24282089 -2010.41762191]
 [-1850.61201691 -1850.61201691 -2006.06546282]
 [-1853.0199987  -1853.0199987  -2001.41997967]
 [-1865.88024082 -1865.88024082 -1985.74259421]
 [-1876.75175374 -1876.75175374 -1977.63819329]
 [-1905.40870557 -1905.40870557 -1965.34936808]
 [-1916.14466218 -1916.14466218 -1957.70974021]
 [-1919.66118149 -1919.66118149 -1957.71201915]
 [-1923.0154348  -1923.0154348  -1952.52269426]
 [           nan            nan            nan]]
pca_f 37
(54, 1805375)
ll  for production factors 37
[[-1841.4109122  -1841.4109122  -2014.75281017]
 [-1845.80452527 -1845.80452527 -2010.25084538]
 [-1850.15628165 -1850.15628165 -2005.93613626]
 [-1852.53944339 -1852.53944339 -2001.32552219]
 [-1865.38066774 -1865.38066774 -1985.70379884]
 [-1876.24265343 -1876.24265343 -1977.60985877]
 [-1904.92798225 -1904.92798225 -1965.31295034]
 [-1915.68272369 -1915.68272369 -1957.51895577]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 54 but corresponding boolean dimension is 9



ll   for only important factors 
[[-1841.85881724 -1841.85881724 -2014.97408168]
 [-1846.24280125 -1846.24280125 -2010.46653225]
 [-1850.6119989  -1850.6119989  -2006.11456161]
 [-1853.01998485 -1853.01998485 -2001.46900876]
 [-1865.88024452 -1865.88024452 -1985.78986824]
 [-1876.75178192 -1876.75178192 -1977.68430525]
 [-1905.40879357 -1905.40879357 -1965.38924014]
 [-1916.14478091 -1916.14478091 -1957.74007862]
 [-1919.66130345 -1919.66130345 -1957.74020297]
 [-1923.01559031 -1923.01559031 -1952.53990408]
 [           nan            nan            nan]]
pca_f 38
(53, 1805375)
ll  for production factors 38
[[-1841.80288774 -1841.80288774 -2015.20563065]
 [-1846.17197267 -1846.17197267 -2010.77717418]
 [-1850.5401739  -1850.5401739  -2006.39135431]
 [-1852.95108529 -1852.95108529 -2001.74031385]
 [-1865.78195381 -1865.78195381 -1986.06721997]
 [-1876.68628384 -1876.68628384 -1977.90444516]
 [-1905.33655    -1905.33655    -1965.54813205]
 [-1916.08892441 -1916.08892441 -1957.75988095]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 53 but corresponding boolean dimension is 8



ll   for only important factors 
[[-1841.85875485 -1841.85875485 -2014.98381459]
 [-1846.24273396 -1846.24273396 -2010.47640666]
 [-1850.6119302  -1850.6119302  -2006.12439247]
 [-1853.01991227 -1853.01991227 -2001.47873515]
 [-1865.88017755 -1865.88017755 -1985.79916132]
 [-1876.75171163 -1876.75171163 -1977.69322834]
 [-1905.40871136 -1905.40871136 -1965.39661902]
 [-1916.14470358 -1916.14470358 -1957.74506572]
 [-1919.66121981 -1919.66121981 -1957.74476379]
 [-1923.01550219 -1923.01550219 -1952.54247368]
 [           nan            nan            nan]]
pca_f 39
(52, 1805375)
ll  for production factors 39
[[-1841.69628321 -1841.69628321 -2015.1516364 ]
 [-1846.06777787 -1846.06777787 -2010.65482586]
 [-1850.4432657  -1850.4432657  -2006.29947838]
 [-1852.84765563 -1852.84765563 -2001.60786731]
 [-1865.71339278 -1865.71339278 -1985.85214523]
 [-1876.51547818 -1876.51547818 -1977.82158043]
 [-1905.14613965 -1905.14613965 -1965.6164392 ]
 [-1915.8585862  -1915.8585862  -1957.82517878]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 52 but corresponding boolean dimension is 7



ll   for only important factors 
[[-1841.85858497 -1841.85858497 -2014.96825919]
 [-1846.24255052 -1846.24255052 -2010.46104364]
 [-1850.61174021 -1850.61174021 -2006.10928706]
 [-1853.01970506 -1853.01970506 -2001.46403316]
 [-1865.87994405 -1865.87994405 -1985.78641043]
 [-1876.75143017 -1876.75143017 -1977.68130122]
 [-1905.40833009 -1905.40833009 -1965.3869756 ]
 [-1916.14432156 -1916.14432156 -1957.73768809]
 [-1919.6608182  -1919.6608182  -1957.73827076]
 [-1923.01506055 -1923.01506055 -1952.53846862]
 [           nan            nan            nan]]
pca_f 40
(51, 1805375)
ll  for production factors 40
[[-1841.66242574 -1841.66242574 -2015.01202493]
 [-1846.02806169 -1846.02806169 -2010.42564877]
 [-1850.40370403 -1850.40370403 -2006.04969771]
 [-1852.80960415 -1852.80960415 -2001.42907814]
 [-1865.64252321 -1865.64252321 -1985.53350232]
 [-1876.50722536 -1876.50722536 -1977.43998048]
 [-1905.12155461 -1905.12155461 -1965.12712788]
 [-1915.81738961 -1915.81738961 -1957.45739537]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 51 but corresponding boolean dimension is 6



ll   for only important factors 
[[-1841.85875425 -1841.85875425 -2014.98380149]
 [-1846.24273201 -1846.24273201 -2010.47636923]
 [-1850.61192862 -1850.61192862 -2006.12436379]
 [-1853.01990996 -1853.01990996 -2001.47870021]
 [-1865.88017109 -1865.88017109 -1985.79911146]
 [-1876.75170115 -1876.75170115 -1977.69318036]
 [-1905.40869197 -1905.40869197 -1965.39657272]
 [-1916.14469271 -1916.14469271 -1957.74500805]
 [-1919.66120574 -1919.66120574 -1957.74469987]
 [-1923.01548982 -1923.01548982 -1952.54240746]
 [           nan            nan            nan]]
pca_f 41
(50, 1805375)
ll  for production factors 41
[[-1841.69578771 -1841.69578771 -2015.2944405 ]
 [-1846.07982812 -1846.07982812 -2010.75189626]
 [-1850.43362612 -1850.43362612 -2006.38951497]
 [-1852.84044691 -1852.84044691 -2001.73119696]
 [-1865.75826906 -1865.75826906 -1985.92330547]
 [-1876.62139486 -1876.62139486 -1977.79808479]
 [-1905.27986204 -1905.27986204 -1965.51601744]
 [-1915.97935168 -1915.97935168 -1957.75617523]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 50 but corresponding boolean dimension is 5



ll   for only important factors 
[[-1841.85876645 -1841.85876645 -2014.97348456]
 [-1846.24274576 -1846.24274576 -2010.46601458]
 [-1850.61194225 -1850.61194225 -2006.1139477 ]
 [-1853.01992601 -1853.01992601 -2001.4683015 ]
 [-1865.88019172 -1865.88019172 -1985.78881364]
 [-1876.75172261 -1876.75172261 -1977.68294684]
 [-1905.40871305 -1905.40871305 -1965.38739454]
 [-1916.14469481 -1916.14469481 -1957.73777035]
 [-1919.66121368 -1919.66121368 -1957.73787375]
 [-1923.01548552 -1923.01548552 -1952.53793594]
 [           nan            nan            nan]]
pca_f 42
(49, 1805375)
ll  for production factors 42
[[-1841.77998756 -1841.77998756 -2014.86262555]
 [-1846.1619271  -1846.1619271  -2010.34585179]
 [-1850.54281954 -1850.54281954 -2005.97206812]
 [-1852.96293729 -1852.96293729 -2001.33796332]
 [-1865.76681449 -1865.76681449 -1985.55166732]
 [-1876.58579952 -1876.58579952 -1977.48761001]
 [-1905.22801771 -1905.22801771 -1965.25677797]
 [-1915.95592608 -1915.95592608 -1957.63397382]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 49 but corresponding boolean dimension is 4



ll   for only important factors 
[[-1841.85878234 -1841.85878234 -2014.93524373]
 [-1846.24275609 -1846.24275609 -2010.42760097]
 [-1850.61195103 -1850.61195103 -2006.07540272]
 [-1853.01993134 -1853.01993134 -2001.4298553 ]
 [-1865.88018148 -1865.88018148 -1985.75202174]
 [-1876.75169137 -1876.75169137 -1977.64722236]
 [-1905.40863637 -1905.40863637 -1965.35683742]
 [-1916.14459515 -1916.14459515 -1957.71482538]
 [-1919.66111152 -1919.66111152 -1957.71667526]
 [-1923.01535745 -1923.01535745 -1952.52534289]
 [           nan            nan            nan]]
pca_f 43
(48, 1805375)
ll  for production factors 43
[[-1841.72743622 -1841.72743622 -2014.26002907]
 [-1846.10023321 -1846.10023321 -2009.73805385]
 [-1850.46466207 -1850.46466207 -2005.36918076]
 [-1852.87691006 -1852.87691006 -2000.71929065]
 [-1865.73243959 -1865.73243959 -1985.08835816]
 [-1876.60260658 -1876.60260658 -1976.97072426]
 [-1905.29333265 -1905.29333265 -1964.79242712]
 [-1916.02903218 -1916.02903218 -1957.12372617]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 48 but corresponding boolean dimension is 3



ll   for only important factors 
[[-1841.85878234 -1841.85878234 -2014.93524373]
 [-1846.24275609 -1846.24275609 -2010.42760097]
 [-1850.61195103 -1850.61195103 -2006.07540272]
 [-1853.01993134 -1853.01993134 -2001.4298553 ]
 [-1865.88018148 -1865.88018148 -1985.75202174]
 [-1876.75169137 -1876.75169137 -1977.64722236]
 [-1905.40863637 -1905.40863637 -1965.35683742]
 [-1916.14459515 -1916.14459515 -1957.71482538]
 [-1919.66111152 -1919.66111152 -1957.71667526]
 [-1923.01535745 -1923.01535745 -1952.52534289]
 [           nan            nan            nan]]
pca_f 44
(47, 1805375)
ll  for production factors 44
[[-1841.81513914 -1841.81513914 -2014.94229285]
 [-1846.19463827 -1846.19463827 -2010.46186871]
 [-1850.56746371 -1850.56746371 -2006.11337767]
 [-1852.98452531 -1852.98452531 -2001.44915692]
 [-1865.85572812 -1865.85572812 -1985.81620981]
 [-1876.72501914 -1876.72501914 -1977.68167722]
 [-1905.37023057 -1905.37023057 -1965.33140749]
 [-1916.08102807 -1916.08102807 -1957.62969839]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 47 but corresponding boolean dimension is 2



ll   for only important factors 
[[-1841.85875682 -1841.85875682 -2014.98388125]
 [-1846.24273737 -1846.24273737 -2010.47650883]
 [-1850.61193402 -1850.61193402 -2006.12449921]
 [-1853.01991858 -1853.01991858 -2001.47888237]
 [-1865.88018667 -1865.88018667 -1985.79929518]
 [-1876.75172136 -1876.75172136 -1977.69333472]
 [-1905.40872661 -1905.40872661 -1965.39671173]
 [-1916.14471628 -1916.14471628 -1957.74516679]
 [-1919.66123563 -1919.66123563 -1957.74486128]
 [-1923.01551494 -1923.01551494 -1952.54255394]
 [           nan            nan            nan]]
pca_f 45
(46, 1805375)
ll  for production factors 45
[[-1841.72555784 -1841.72555784 -2014.99930252]
 [-1846.10239831 -1846.10239831 -2010.49341442]
 [-1850.43412045 -1850.43412045 -2006.17141958]
 [-1852.84024327 -1852.84024327 -2001.54083241]
 [-1865.66221038 -1865.66221038 -1985.92284804]
 [-1876.49856411 -1876.49856411 -1977.87457002]
 [-1905.10432368 -1905.10432368 -1965.66253494]
 [-1915.84216366 -1915.84216366 -1958.02913441]


/home/oleg/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:31: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 46 but corresponding boolean dimension is 1



ll   for only important factors 
[[-1841.85878234 -1841.85878234 -2014.93524373]
 [-1846.24275609 -1846.24275609 -2010.42760097]
 [-1850.61195103 -1850.61195103 -2006.07540272]
 [-1853.01993134 -1853.01993134 -2001.4298553 ]
 [-1865.88018148 -1865.88018148 -1985.75202174]
 [-1876.75169137 -1876.75169137 -1977.64722236]
 [-1905.40863637 -1905.40863637 -1965.35683742]
 [-1916.14459515 -1916.14459515 -1957.71482538]
 [-1919.66111152 -1919.66111152 -1957.71667526]
 [-1923.01535745 -1923.01535745 -1952.52534289]
 [           nan            nan            nan]]


In [55]:
ss_TT = np.array([item for sublist in student_t_factors for item in sublist])
name_TT = np.array([item for sublist in names_factors for item in sublist])
ss_TT[ss_TT >2].shape

(70,)

In [56]:
def lists_to_list(_list):
    _x =[]
    for y in [x for x in _list]:
        _x = np.append(_x, y) 
    return _x

In [57]:
_names_factors = lists_to_list(names_factors)
student_factors = lists_to_list(student_t_factors)

In [58]:
_names_factors

array(['pca_f1*pca_f1', 'pca_f2*pca_f1', 'pca_f3*pca_f1', ...,
       'pca_f44*pca_f44', 'pca_f45*pca_f44', 'pca_f45*pca_f45'], 
      dtype='|S32')

In [59]:
st_name_factors = [(x, y) for x,y in zip(_names_factors, student_factors)]
st_name_factors.sort(key =lambda x: x[1], reverse =True)

In [60]:
st_name_factors

[('pca_f30*pca_f12', 4.0093495980333778),
 ('pca_f17*pca_f16', 3.3430922236443141),
 ('pca_f36*pca_f36', 3.1847181927487553),
 ('pca_f36*pca_f12', 3.0236772029847714),
 ('pca_f26*pca_f25', 2.8812223244373159),
 ('pca_f14*pca_f14', 2.881133854345943),
 ('pca_f19*pca_f16', 2.7913099213218349),
 ('pca_f36*pca_f26', 2.7910373967245841),
 ('pca_f29*pca_f12', 2.7897011537947316),
 ('pca_f25*pca_f19', 2.7885353233737793),
 ('pca_f14*pca_f4', 2.7668803088331644),
 ('pca_f45*pca_f16', 2.7155497725354754),
 ('pca_f2*pca_f1', 2.6922745282347225),
 ('pca_f8*pca_f2', 2.6561880285077604),
 ('pca_f38*pca_f25', 2.5857033721238722),
 ('pca_f45*pca_f45', 2.5855482715160849),
 ('pca_f36*pca_f15', 2.5662333350968853),
 ('pca_f44*pca_f17', 2.5493759307867361),
 ('pca_f34*pca_f14', 2.5472255833196402),
 ('pca_f25*pca_f22', 2.5092425198890767),
 ('pca_f22*pca_f9', 2.4994972421661772),
 ('pca_f42*pca_f11', 2.4790187071063703),
 ('pca_f41*pca_f7', 2.4763490452845134),
 ('pca_f22*pca_f22', 2.4738334211334942),


In [30]:
def int_factors(_list):
    list_factors =[]
    _list = [x.split('*') for x in _list]
    for _x_str in _list:
        list_factors.append([int(filter(str.isdigit,x)) for x in _x_str])
    return np.array(list_factors)

In [61]:
def list_factor(st_name_factors, top = 20):
    list_factors =[]
    _list = [x[0] for x in st_name_factors[:top]]
    _list = [x.split('*') for x in _list]
    for _x_str in _list:
        list_factors.append([int(filter(str.isdigit,x)) for x in _x_str])
    return np.array(list_factors)

In [69]:
factors_numbers = list_factor(st_name_factors, 10) -1

In [77]:
def polinom_factors(factors_numbers, top =10, factors =factors):
    
    new_factors = np.full((top, factors.shape[1]), np.nan)
    for i,j in enumerate(factors_numbers):
        new_factors[i,:] = factors[j[0],:]*factors[j[1],:]
    return new_factors

In [82]:
def important_polinoms_factors(names_factors, student_t_factors, top =30, factors =factors):
    
    #list of lists in one list
    names_factors = lists_to_list(names_factors)
    student_t_factors = lists_to_list(student_t_factors)
    #sort by values of student_t_factors, with remember of names factors
    names_student_factors = [(x, y) for x,y in zip(names_factors, student_factors)]
    names_student_factors.sort(key =lambda x: x[1], reverse =True)
    #list of top factors in int type
    factors_numbers = list_factor(names_student_factors, top =top) -1
    
    return polinom_factors(factors_numbers, top =top, factors =factors)

In [91]:
new_factors = np.vstack((pca_factors, 
            important_polinoms_factors(names_factors, student_t_factors, 5, pca_factors)))
new_factors.shape

(50, 1805375)

In [97]:
new_model = TSModel(new_factors, tsav, pars)

new_model.fit_slices(fit_afresh=True)

print 'll'
print new_model.stats1.ll

ll
[[-1840.16791435 -1840.16791435 -2014.37865554]
 [-1844.55461153 -1844.55461153 -2009.97149907]
 [-1848.84877571 -1848.84877571 -2005.72041167]
 [-1851.26792442 -1851.26792442 -2001.17716753]
 [-1864.05845882 -1864.05845882 -1985.64674071]
 [-1874.88170041 -1874.88170041 -1977.70550239]
 [-1903.41544102 -1903.41544102 -1965.7915072 ]
 [-1913.90161721 -1913.90161721 -1958.45556158]
 [-1917.34963979 -1917.34963979 -1958.457847  ]
 [-1920.8535894  -1920.8535894  -1953.25638537]
 [           nan            nan            nan]]


In [93]:
from thbmodel.prediction.tools.clustering import write_dic_to_simdata
write_dic_to_simdata('model_new_factors.p', new_model.step1probs, new_model.eff_coefs, new_model.params.oos, av=av)

In [85]:
old_model = TSModel(factors, tsav, pars)
old_model.fit_slices(fit_afresh=True)

print 'll'
print old_model.stats1.ll

ll
[[-1841.71134254 -1841.71134254 -2014.22627609]
 [-1846.09933267 -1846.09933267 -2009.80810427]
 [-1850.45108524 -1850.45108524 -2005.42403158]
 [-1852.84651257 -1852.84651257 -2000.77815071]
 [-1865.64182041 -1865.64182041 -1985.37827819]
 [-1876.45454829 -1876.45454829 -1977.56090486]
 [-1905.03126923 -1905.03126923 -1965.26265245]
 [-1915.51635675 -1915.51635675 -1957.59727056]
 [-1918.96163692 -1918.96163692 -1957.71061385]
 [-1922.14635182 -1922.14635182 -1952.90889816]
 [           nan            nan            nan]]


In [45]:
from thbmodel.prediction.tools.clustering import write_dic_to_simdata
write_dic_to_simdata('old_model.p', old_model.step1probs, old_model.eff_coefs, old_model.params.oos, av=av)

In [ ]:
len(np.unique(av.event_id[pars.is1])), len(np.unique(av.event_id[pars.oos]))

In [ ]:
import pickle
with open('old_model.pickle', 'wb') as f:
    pickle.dump(tsmod, f)

In [ ]:
import torch

In [ ]:
x = torch.FloatTensor(1024, 1024).uniform_()

In [ ]:
x = x.cuda()

In [ ]:
import tensorflow as tf
tf.__version__

In [ ]:
%%timeit
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
a = a.cuda()
b = b.cuda()
c = a.mul_(b)

In [ ]:
%%timeit
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.mul_(b)